/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Main.Checking;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class CreateCheckings extends javax.swing.JPanel {

    /**
     * Creates new form CreateCheckings
     */
    Checking check;
    public CreateCheckings(Checking check) {
        this.check=check;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbllast = new javax.swing.JLabel();
        lblphn = new javax.swing.JLabel();
        BtnCreate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtBname = new javax.swing.JTextField();
        TxtRouting = new javax.swing.JTextField();
        TxtAccbalance = new javax.swing.JTextField();
        TxtAcc = new javax.swing.JTextField();
        TxtType = new javax.swing.JTextField();
        lblBankname = new javax.swing.JLabel();

        lbllast.setText("Routing Number:");

        lblphn.setText("Account Number:");

        BtnCreate.setText("CREATE");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("CREATE CHECKINGS ACCOUNT");

        lbldob.setText("Account Balance:");

        jLabel5.setText("Account Type :");

        TxtBname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBnameActionPerformed(evt);
            }
        });

        TxtRouting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRoutingActionPerformed(evt);
            }
        });

        TxtAccbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAccbalanceActionPerformed(evt);
            }
        });

        TxtAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAccActionPerformed(evt);
            }
        });

        TxtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTypeActionPerformed(evt);
            }
        });

        lblBankname.setText("Bank Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(lbldob)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblphn)
                                .addComponent(lbllast, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblBankname, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtAccbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtType, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(BtnCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankname)
                    .addComponent(TxtBname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllast)
                    .addComponent(TxtRouting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphn)
                    .addComponent(TxtAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldob)
                    .addComponent(TxtAccbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnCreate)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        // TODO add your handling code here:
        check.setName(TxtBname.getText());
        check.setAccbalance(TxtAccbalance.getText());
        check.setAccnumber(TxtAcc.getText());
        check.setRoutingnumber(TxtRouting.getText());
        check.setAcctype(TxtType.getText());
        JOptionPane.showMessageDialog(this,"Account Details Added!!");
       
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void TxtBnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBnameActionPerformed

    private void TxtRoutingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRoutingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRoutingActionPerformed

    private void TxtAccbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAccbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAccbalanceActionPerformed

    private void TxtAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAccActionPerformed

    private void TxtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreate;
    private javax.swing.JTextField TxtAcc;
    private javax.swing.JTextField TxtAccbalance;
    private javax.swing.JTextField TxtBname;
    private javax.swing.JTextField TxtRouting;
    private javax.swing.JTextField TxtType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBankname;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lbllast;
    private javax.swing.JLabel lblphn;
    // End of variables declaration//GEN-END:variables
}
