/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Main.Address;
import Main.Checking;
import Main.Demographic;
import Main.License;
import Main.MedicalRecord;
import Main.Savings;

/**
 *
 * @author Dell
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Demographic demo;
    Checking check;
    Address add;
    License lic;
    MedicalRecord medic;
    Savings save;
    ViewReport report;

    public MainJFrame() {
        initComponents();
        demo = new Demographic();
        check = new Checking();
        add = new Address();
        lic = new License();
        medic = new MedicalRecord();
        save = new Savings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel5 = new javax.swing.JPanel();
        BtnCreateD = new javax.swing.JButton();
        BtnViewD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnCreateAd = new javax.swing.JButton();
        BtnViewAd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        BtnCreateSa = new javax.swing.JButton();
        BtnViewSa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnCreateCh = new javax.swing.JButton();
        BtnViewCh = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        BtnViewDr = new javax.swing.JButton();
        BtnCreateDr = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        BtnViewMe = new javax.swing.JButton();
        BtnCreateMe = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        BtnViewReport = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(250);

        BtnCreateD.setText("Create");
        BtnCreateD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateDActionPerformed(evt);
            }
        });

        BtnViewD.setText("View");
        BtnViewD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewDActionPerformed(evt);
            }
        });

        jLabel2.setText("Demographic Information");

        BtnCreateAd.setText("Create");
        BtnCreateAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateAdActionPerformed(evt);
            }
        });

        BtnViewAd.setText("View");
        BtnViewAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewAdActionPerformed(evt);
            }
        });

        jLabel3.setText("Saving Account Information");

        BtnCreateSa.setText("Create");
        BtnCreateSa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateSaActionPerformed(evt);
            }
        });

        BtnViewSa.setText("View");
        BtnViewSa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewSaActionPerformed(evt);
            }
        });

        jLabel5.setText("Checking Account Information");

        BtnCreateCh.setText("Create");
        BtnCreateCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateChActionPerformed(evt);
            }
        });

        BtnViewCh.setText("View");
        BtnViewCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewChActionPerformed(evt);
            }
        });

        jLabel1.setText("Address Information");

        jLabel4.setText("Driver’s License Information");

        BtnViewDr.setText("View");
        BtnViewDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewDrActionPerformed(evt);
            }
        });

        BtnCreateDr.setText("Create");
        BtnCreateDr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateDrActionPerformed(evt);
            }
        });

        jLabel6.setText("Medical Record");

        BtnViewMe.setText("View");
        BtnViewMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewMeActionPerformed(evt);
            }
        });

        BtnCreateMe.setText("Create");
        BtnCreateMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateMeActionPerformed(evt);
            }
        });

        jLabel7.setText("Report");

        BtnViewReport.setText("View Report");
        BtnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(BtnCreateD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnViewD))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(BtnCreateAd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnViewAd))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(BtnCreateMe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnViewMe))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(BtnCreateSa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnViewSa))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(BtnCreateCh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnViewCh))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(BtnCreateDr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnViewDr))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel7)))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(BtnViewReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewD)
                    .addComponent(BtnCreateD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewAd)
                    .addComponent(BtnCreateAd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewSa)
                    .addComponent(BtnCreateSa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewCh)
                    .addComponent(BtnCreateCh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewDr)
                    .addComponent(BtnCreateDr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnViewMe)
                    .addComponent(BtnCreateMe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnViewReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateDActionPerformed
        // TODO add your handling code here:
        CreateDemo createdemo = new CreateDemo(demo);
        jSplitPane1.setRightComponent(createdemo);

    }//GEN-LAST:event_BtnCreateDActionPerformed

    private void BtnViewAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewAdActionPerformed
        // TODO add your handling code here:
        ViewAddress address = new ViewAddress(add);
        jSplitPane1.setRightComponent(address);
    }//GEN-LAST:event_BtnViewAdActionPerformed

    private void BtnViewDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewDActionPerformed
        // TODO add your handling code here:
        ViewDemo viewdemo = new ViewDemo(demo);
        jSplitPane1.setRightComponent(viewdemo);

    }//GEN-LAST:event_BtnViewDActionPerformed

    private void BtnCreateAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateAdActionPerformed
        // TODO add your handling code here:
        CreateAddress address = new CreateAddress(add);
        jSplitPane1.setRightComponent(address);
    }//GEN-LAST:event_BtnCreateAdActionPerformed

    private void BtnCreateSaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateSaActionPerformed
        // TODO add your handling code here:
        CreateSavings createsavings = new CreateSavings(save);
        jSplitPane1.setRightComponent(createsavings);
    }//GEN-LAST:event_BtnCreateSaActionPerformed

    private void BtnCreateChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateChActionPerformed
        // TODO add your handling code here:
        CreateCheckings createcheckings = new CreateCheckings(check);
        jSplitPane1.setRightComponent(createcheckings);
    }//GEN-LAST:event_BtnCreateChActionPerformed

    private void BtnCreateDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateDrActionPerformed
        // TODO add your handling code here:
        CreateLicense createlicense = new CreateLicense(lic);
        jSplitPane1.setRightComponent(createlicense);
    }//GEN-LAST:event_BtnCreateDrActionPerformed

    private void BtnCreateMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateMeActionPerformed
        // TODO add your handling code here:
        CreateMedical createmedical = new CreateMedical(medic);
        jSplitPane1.setRightComponent(createmedical);
    }//GEN-LAST:event_BtnCreateMeActionPerformed

    private void BtnViewSaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewSaActionPerformed
        // TODO add your handling code here:
        ViewSavings viewsavings=new ViewSavings(save);
        jSplitPane1.setRightComponent(viewsavings);
    }//GEN-LAST:event_BtnViewSaActionPerformed

    private void BtnViewChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewChActionPerformed
        // TODO add your handling code here:
        ViewCheckings viewcheckings=new ViewCheckings(check);
        jSplitPane1.setRightComponent(viewcheckings);
    }//GEN-LAST:event_BtnViewChActionPerformed

    private void BtnViewDrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewDrActionPerformed
        // TODO add your handling code here:
        ViewLicense viewlicense=new ViewLicense(lic);
        jSplitPane1.setRightComponent(viewlicense);
    }//GEN-LAST:event_BtnViewDrActionPerformed

    private void BtnViewMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewMeActionPerformed
        // TODO add your handling code here:
        ViewMedical viewmedical=new ViewMedical(medic);
        jSplitPane1.setRightComponent(viewmedical);
    }//GEN-LAST:event_BtnViewMeActionPerformed

    private void BtnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewReportActionPerformed
        // TODO add your handling code here:
         ViewReport viewreport=new ViewReport(demo,lic,save,check,add,medic,report);
        jSplitPane1.setRightComponent(viewreport);
    }//GEN-LAST:event_BtnViewReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreateAd;
    private javax.swing.JButton BtnCreateCh;
    private javax.swing.JButton BtnCreateD;
    private javax.swing.JButton BtnCreateDr;
    private javax.swing.JButton BtnCreateMe;
    private javax.swing.JButton BtnCreateSa;
    private javax.swing.JButton BtnViewAd;
    private javax.swing.JButton BtnViewCh;
    private javax.swing.JButton BtnViewD;
    private javax.swing.JButton BtnViewDr;
    private javax.swing.JButton BtnViewMe;
    private javax.swing.JButton BtnViewReport;
    private javax.swing.JButton BtnViewSa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
