/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Main.Demographic;

/**
 *
 * @author Dell
 */
public class ViewDemo extends javax.swing.JPanel {

    /**
     * Creates new form CreateDemo
     */
    Demographic demo;
    public ViewDemo(Demographic demo) {
        initComponents();
        this.demo=demo;
        displayProduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lbllast = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblphn = new javax.swing.JLabel();
        TxtWeight = new javax.swing.JTextField();
        lblSsn = new javax.swing.JLabel();
        TxtSSN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbldob = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtFname = new javax.swing.JTextField();
        Txtlname = new javax.swing.JTextField();
        TxtDob = new javax.swing.JTextField();
        TxtPhone = new javax.swing.JTextField();
        TxtAge = new javax.swing.JTextField();
        lblheight = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        TxtHeight = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbllast.setText("Last Name :");

        lblWeight.setText("Weight:");

        lblphn.setText("Phone Number :");

        TxtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtWeightActionPerformed(evt);
            }
        });

        lblSsn.setText("Social Security Number:");

        TxtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSSNActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("VIEW");

        lbldob.setText("Date of Birth:");

        jLabel5.setText("Age:");

        TxtFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFnameActionPerformed(evt);
            }
        });

        Txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtlnameActionPerformed(evt);
            }
        });

        TxtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDobActionPerformed(evt);
            }
        });

        TxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPhoneActionPerformed(evt);
            }
        });

        TxtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAgeActionPerformed(evt);
            }
        });

        lblheight.setText("Height:");

        lblname.setText("First Name :");

        TxtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSsn)
                        .addGap(37, 37, 37)
                        .addComponent(TxtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbldob, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblphn)
                                .addComponent(lbllast, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblname, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblheight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblWeight, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(TxtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllast)
                    .addComponent(Txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphn)
                    .addComponent(TxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldob)
                    .addComponent(TxtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblheight)
                    .addComponent(TxtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(TxtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSsn)
                    .addComponent(TxtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtWeightActionPerformed

    private void TxtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSSNActionPerformed

    private void TxtFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFnameActionPerformed

    private void TxtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtlnameActionPerformed

    private void TxtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDobActionPerformed

    private void TxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPhoneActionPerformed

    private void TxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAgeActionPerformed

    private void TxtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHeightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtAge;
    private javax.swing.JTextField TxtDob;
    private javax.swing.JTextField TxtFname;
    private javax.swing.JTextField TxtHeight;
    private javax.swing.JTextField TxtPhone;
    private javax.swing.JTextField TxtSSN;
    private javax.swing.JTextField TxtWeight;
    private javax.swing.JTextField Txtlname;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lbldob;
    private javax.swing.JLabel lblheight;
    private javax.swing.JLabel lbllast;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblphn;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
         TxtFname.setText(demo.getFname());
         Txtlname.setText(demo.getLname());
         TxtWeight.setText(demo.getWeight());
         TxtHeight.setText(demo.getHeight());
         TxtAge.setText(demo.getAge());
         TxtSSN.setText(demo.getSsn());
         TxtDob.setText(demo.getDob());
         TxtPhone.setText(demo.getPhnumber());
         
       
   
    
    
    }
}
